### ISSUE TITLE
install and setup

### ISSUE THREAD

**Issue by Hessel91** [chkilel/vitewind-theme#1]
Hi, 
I have installed the plugin and the theme and followed your instructions, however, I am not able to configure it correctly. 
I run npm install, and configure the theme and plugin settings. 
everything works however the front-end theme layout is missing css? 
the console returns 4 errors
```
GET http://localhost/@vite/client net::ERR_ABORTED 404 (Not Found)
localhost/:87 GET http://localhost/resources/js/app.js net::ERR_ABORTED 404 (Not Found)
localhost/:88 GET http://localhost/resources/js/home.js net::ERR_ABORTED 404 (Not Found)
localhost/:86 GET http://localhost/@vite/client net::ERR_ABORTED 404 (Not Found)  

```

If I try to run `npm run watch`  the script is missing. 

```
$ npm run watch
npm ERR! missing script: watch

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hesse\AppData\Roaming\npm-cache\_logs\2022-01-27T23_02_46_021Z-debug.log
```

If I switch dev port from 80  (lxamp localhost port) to 3000 the console return other errors:

```
Failed to load resource: net::ERR_CONNECTION_REFUSED                        client:1
app.js:1 Failed to load resource: net::ERR_CONNECTION_REFUSED           app.js:1
home.js:1 Failed to load resource: net::ERR_CONNECTION_REFUSED        home.js:1
```

how to proceed from this point?

**Comment by chkilel** [comment]
Hello @Hessel91 
Are you using it with OctoberCMS or WinterCMS, and which version to check please.
Thanks.

**Comment by Hessel91** [comment]
Hi, OctoberCms on localhost >version 2.1.27

**Comment by chkilel** [comment]
hello @Hessel91 

I had a mistake in the doc, the dev command is not `npm run watch` but `npm run dev`
Make sure all `npm` commands `npm install` and `npm run dev` are run from theme directory  not from the project root.
Please check and give me your feedback.
If you need help, you can find me on slack, my username is `Chkilel`, i'll walk you through the set up steps 
Thanks for reporting.
