### ISSUE TITLE
Does this theme support HRM?

### ISSUE THREAD

**Issue by khalidchawtany** [chkilel/vitewind-theme#2]
Thanks for this awesome theme.

Does this theme support HRM or it does full reload on every change?

I always get full reloads making changes to my pages.

**Comment by chkilel** [comment]
Hi @khalidchawtany 
At this time it does not support HMR, I did't find a way to implement it.
Thanks Khalid

**Comment by chkilel** [comment]
HRM works for JS and CSS files, but if changes are made to the template files the server needs to reload the page to reflect those changes.
Hope this clarify your question @khalidchawtany.

**Comment by khalidchawtany** [comment]
Thanks that is very nice. I wish it worked for templates too. However, I know that it is almost impossible to implement :(
